version: '3.8'

networks:
    app-network:
services:
  database:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    image: springleo/backend:latest
    container_name: backend
    environment:
      DB_HOST: mysql-db.database_default
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: app_db
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    image: springleo/frontend:latest 
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-network

