apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-app.fullname" . }}
  labels: 
    {{- include "backend-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.servicePort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector: 
    {{- include "backend-app.selectorLabels" . | nindent 4 }}
